defaults:
  - data_feed: jdata
  - stratergy: golden_cross
  - broker: zerodha
  - _self_


cerebro:
  stdstats: True
  oldbuysell: True
  preload: False

data_feed:
  name: data_live
  symbol_name: NIFTYBEES
  filepath: ../../data/prod/NIFTY 50/2022/02/14.csv

live: True
data_feed_test: False
broker_test: False
plot: True

broker:
  cash: 20000
