defaults:
  - data_feed: index_live
  - stratergy: golden_cross
  - _self_


cerebro:
  live: True
  stdstats: True
  oldbuysell: True

data_feed:
  index_name: NIFTY 50

test: True

broker:
  cash: 500000
